version: '3'


services:
  app:
    build: .
    entrypoint: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    volumes:
      - .:/homr/node/app

redis:
  image: redis:6.2.6-alpine3.14
